# Generated by Django 5.0.1 on 2024-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="registration_date",
            field=models.DateField(),
        ),
    ]
