# Generated by Django 5.0.1 on 2024-06-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0002_alter_vehicle_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplaterecognitionrecord",
            name="record_time",
            field=models.DateField(),
        ),
    ]
