# Generated by Django 5.0.1 on 2024-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0003_alter_licenseplaterecognitionrecord_record_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplaterecognitionrecord",
            name="record_time",
            field=models.DateTimeField(),
        ),
    ]
