# Generated by Django 5.0.1 on 2024-06-03 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0004_alter_licenseplaterecognitionrecord_record_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseplaterecognitionrecord",
            name="record_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="licenseplaterecognitionrecord",
            name="record_time",
            field=models.TimeField(),
        ),
    ]
