# Generated by Django 5.0.1 on 2024-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0005_licenseplaterecognitionrecord_record_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplaterecognitionrecord",
            name="junction",
            field=models.CharField(max_length=100),
        ),
    ]
